image_width: 1080
image_height: 1920
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1540.05806,    0.     ,  597.66783,
            0.     , 1536.03404, 1013.52471,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.013225, -0.207093, 0.011020, 0.012364, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1535.94678,    0.     ,  605.87189,    0.     ,
            0.     , 1478.38989, 1046.75671,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
